####################################################################################
# Template for Testing CF template
# Created by:  Prakash Bulusu
# Date: 19/12/2017
####################################################################################
 
AWSTemplateFormatVersion: 2010-09-09
Description: "Cloud formation template for testing CF through Jenkins"
  
#################################### AWS Resources ####################################
 Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-aa2ea6d0
      AvailabilityZone: us-east-1a
